# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/OneDrive - HKUST Connect/Lab/color_filter_testing_FAST_VSRSION/cons/top_io.xdc

# XDC: D:/OneDrive - HKUST Connect/Lab/color_filter_testing_FAST_VSRSION/cons/top_time.xdc

# IP: D:/OneDrive - HKUST Connect/Lab/color_filter_testing_FAST_VSRSION/ips/glb_clk_src/glb_clk_src.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==glb_clk_src || ORIG_REF_NAME==glb_clk_src} -quiet] -quiet
