# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/KANG Jian/Desktop/color_filter_testing/cons/top_io.xdc

# XDC: C:/Users/KANG Jian/Desktop/color_filter_testing/cons/top_time.xdc

# IP: C:/Users/KANG Jian/Desktop/color_filter_testing/ips/glb_clk_src/glb_clk_src.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==glb_clk_src || ORIG_REF_NAME==glb_clk_src} -quiet] -quiet
